# Generated by Django 3.1.1 on 2021-02-23 09:44

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about-us-images/%Y/%m/%d/', verbose_name='Image')),
                ('video', models.FileField(blank=True, null=True, upload_to='about-us-videos/%Y/%m/%d/', verbose_name='Video')),
                ('description', models.TextField(verbose_name='Description')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'About Us',
                'ordering': ['pub_date'],
            },
        ),
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='article/%Y/%m/%d/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=300, null=True, verbose_name='Caption')),
                ('title', models.CharField(max_length=350, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(max_length=400)),
                ('description', models.TextField(verbose_name='Description')),
                ('author', models.CharField(default='Mehroj', max_length=50, verbose_name='Author')),
                ('view_counter', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Published')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['published_at', 'updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PortFolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='portfolio/%Y/%m/%d/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=300, null=True, verbose_name='Caption')),
                ('name', models.CharField(max_length=300, verbose_name='Name')),
                ('slug', models.SlugField(max_length=320)),
                ('short_info', models.CharField(default='3D model', max_length=500, verbose_name='Short Info')),
                ('description', models.TextField(verbose_name='Description')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'PortFolio',
                'ordering': ['published_at', 'updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, null=True, unique=True, verbose_name='Video URL')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/%Y/%m/%d/', verbose_name='Video File')),
                ('title', models.CharField(max_length=300, verbose_name='Video Title')),
                ('description', models.TextField(verbose_name='Video Description')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Videos',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='portfolio-images/%Y/%m/%d/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=300, null=True, verbose_name='Caption:')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_images', to='core.portfolio', verbose_name='3D Model')),
            ],
            options={
                'verbose_name_plural': "Portfolio' Images",
            },
        ),
    ]
