# Generated by Django 3.1.1 on 2021-03-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210304_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cart_field',
            field=models.BooleanField(default=False),
        ),
    ]
