# Generated by Django 3.1.1 on 2021-02-23 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False, verbose_name='Completed')),
                ('date_ordered', models.DateTimeField(auto_now_add=True, verbose_name='Order Date')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Order Date')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_product', to='product.product', verbose_name='Model')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order Model',
                'verbose_name_plural': 'Order Models',
            },
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=300, null=True, verbose_name='Model')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ordered-product/%Y/%m/%d/', verbose_name='Image')),
                ('model_quantity', models.IntegerField(default=0, verbose_name='Model Quantity')),
                ('single_price', models.FloatField(default=0, verbose_name='Price')),
                ('total_price', models.FloatField(default=0, verbose_name='Total Price')),
                ('date_ordered', models.DateTimeField(auto_now_add=True, verbose_name='Ordered Date')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to='cart.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Ordered Models',
                'verbose_name_plural': 'Ordered Models',
                'ordering': ['-date_ordered'],
            },
        ),
    ]
