# Generated by Django 3.1.1 on 2021-03-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='cart_field',
            field=models.BooleanField(default=False),
        ),
    ]
