# Generated by Django 3.1.1 on 2021-03-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_ordereditem_cart_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditem',
            name='cart_field',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cart_field',
            field=models.BooleanField(default=False),
        ),
    ]
